# Site settings
name: 意气而已
email: 372928391@qq.com
author: 李 鑫
url: http://youjiuzidangge.com
resume_site: 
github: https://github.com/luoyan35714/
baseurl: ""
description: 今朝有酒今朝醉，明日愁来明日忧。
meta_description: 李鑫;近处的风景，远处的风景，一个我都不想错过;
motto: 要么不做，要么就做到最好！
banner: 要么不做，要么就做到最好。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: youjiuzidangge
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
