# Site settings
name: 意气而已
email: youjiuzidangge@gmail.com
author: Jason Li
url: http://youjiuzidangge.com
resume_site: 
github: https://github.com/youjiuzidangge/youjiuzidangge.github.io
baseurl: ""
description: 遇饮酒时须饮酒，得高歌处且高歌。
meta_description: Jason;blog;日记;IT;
motto: Don't do or do your best.
banner: 远处的风景，近处的风景，一个我都不想错过。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

future: true
plugins: ['jekyll-paginate']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: youjiuzidangge


# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

baidu_analysis: bc6f1c7c413b46c959303e3bedb94778

github_app_auth_client: Ov23liAQtxPAVYnOUJMZ
github_app_auth_secret: 4673d947ec7f1475d4fe1ff50a834db1378c8963

FB:
  comments :
    provider: github
    duoshuo:
        short_name :  youjiuzidangge
    disqus:
        short_name :
    github:
        client_id: Ov23liAQtxPAVYnOUJMZ
        secret: 4673d947ec7f1475d4fe1ff50a834db1378c8963
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light